# Minimal Spot Guard test configuration - only required options
# This file contains ONLY the necessary configuration for Spot Guard to work

# Global configuration
global:
  region: us-west-2

# Image configuration
image:
  repository: public.ecr.aws/aws-ec2/aws-node-termination-handler
  tag: "v1.21.0"
  pullPolicy: IfNotPresent

# Service account and RBAC
serviceAccount:
  create: true
rbac:
  create: true

# Security context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

# Resource limits
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Logging configuration
logLevel: debug
jsonLogging: true

# IMDS Configuration - MINIMAL for Spot Guard
enableSqsTerminationDraining: false
enableRebalanceMonitoring: true    # REQUIRED - Spot Guard needs rebalance events
enableRebalanceDraining: true      # RECOMMENDED - Handle rebalance events

# Spot Guard Configuration
spotGuard:
  enabled: true
  spotASGName: "my-spot-asg"
  onDemandASGName: "my-ondemand-asg"
  minimumWaitDuration: "5m"
  checkInterval: "30s"
  spotStabilityDuration: "2m"
  maxClusterUtilization: 75
  podEvictionTimeout: "5m"
  cleanupInterval: "10m"
  maxEventAge: "24h"

# AWS configuration
awsRegion: us-west-2
metadataURL: http://169.254.169.254
metadataTries: 3

# Node termination configuration
nodeTerminationGracePeriod: 120
deleteLocalData: true
ignoreDaemonSets: true
podTerminationGracePeriod: 30

# Testing annotations
podAnnotations:
  test.spotguard.io/enabled: "true"
  test.spotguard.io/mode: "minimal"

# Testing labels
podLabels:
  app.kubernetes.io/component: "spot-guard-minimal"
  test.spotguard.io/version: "v1.0.0"
